import { NextResponse } from 'next/server';
import dbConnect from '@/lib/mongodb';
import EV from '@/models/ev';
import Review from '@/models/review';

const initialCars = [
  // --- BYD ---
  {
    brand: 'BYD',
    model: 'Atto 3',
    trim: 'Extended Range',
    price: 859900,
    image: '/images/byd_atto3.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4455,
    width: 1875,
    height: 1615,
    wheelbase: 2720,
    cargoVolume: 440,
    frunkVolume: 0,
    horsepower: 201,
    torque: 310,
    acceleration0To100: 7.3,
    topSpeed: 160,
    driveType: 'FWD',
    batteryCapacity: 60.48,
    batteryType: 'LFP',
    rangeWLTP: 420,
    rangeNEDC: 480,
    rangeCLTC: 510,
    acChargePower: 7,
    dcChargePower: 88,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'BYD',
    model: 'Atto 3',
    trim: 'Standard Range',
    price: 799900,
    image: '/images/byd_atto3.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4455,
    width: 1875,
    height: 1615,
    wheelbase: 2720,
    cargoVolume: 440,
    frunkVolume: 0,
    horsepower: 201,
    torque: 310,
    acceleration0To100: 7.9,
    topSpeed: 160,
    driveType: 'FWD',
    batteryCapacity: 49.92,
    batteryType: 'LFP',
    rangeWLTP: 345,
    rangeNEDC: 410,
    rangeCLTC: 430,
    acChargePower: 7,
    dcChargePower: 70,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'BYD',
    model: 'Dolphin',
    trim: 'Standard Range',
    price: 569900,
    image: '/images/byd_dolphin.png',
    bodyType: 'Hatchback',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4290,
    width: 1770,
    height: 1570,
    wheelbase: 2700,
    cargoVolume: 345,
    frunkVolume: 0,
    horsepower: 94,
    torque: 180,
    acceleration0To100: 12.3,
    topSpeed: 150,
    driveType: 'FWD',
    batteryCapacity: 44.9,
    batteryType: 'LFP',
    rangeWLTP: 340,
    rangeNEDC: 410,
    rangeCLTC: 420,
    acChargePower: 7,
    dcChargePower: 60,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'BYD',
    model: 'Dolphin',
    trim: 'Extended Range',
    price: 699900,
    image: '/images/byd_dolphin.png',
    bodyType: 'Hatchback',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4290,
    width: 1770,
    height: 1570,
    wheelbase: 2700,
    cargoVolume: 345,
    frunkVolume: 0,
    horsepower: 201,
    torque: 310,
    acceleration0To100: 7.0,
    topSpeed: 160,
    driveType: 'FWD',
    batteryCapacity: 60.48,
    batteryType: 'LFP',
    rangeWLTP: 427,
    rangeNEDC: 490,
    rangeCLTC: 500,
    acChargePower: 7,
    dcChargePower: 80,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },

  // --- Tesla ---
  {
    brand: 'Tesla',
    model: 'Model 3',
    trim: 'Rear-Wheel Drive',
    price: 1599000,
    image: '/images/tesla_model3.png',
    bodyType: 'Sedan',
    warrantyYears: 4,
    warrantyKm: 80000,
    length: 4720,
    width: 1850,
    height: 1441,
    wheelbase: 2875,
    cargoVolume: 594,
    frunkVolume: 88,
    horsepower: 283,
    torque: 420,
    acceleration0To100: 6.1,
    topSpeed: 201,
    driveType: 'RWD',
    batteryCapacity: 57.5,
    batteryType: 'LFP',
    rangeWLTP: 513,
    rangeNEDC: 0,
    rangeCLTC: 606,
    acChargePower: 11,
    dcChargePower: 170,
    voltageArchitecture: '400V',
    v2lSupport: false,
    v2lPower: 0
  },
  {
    brand: 'Tesla',
    model: 'Model 3',
    trim: 'Long Range AWD',
    price: 1899000,
    image: '/images/tesla_model3.png',
    bodyType: 'Sedan',
    warrantyYears: 4,
    warrantyKm: 80000,
    length: 4720,
    width: 1850,
    height: 1441,
    wheelbase: 2875,
    cargoVolume: 594,
    frunkVolume: 88,
    horsepower: 498,
    torque: 493,
    acceleration0To100: 4.4,
    topSpeed: 201,
    driveType: 'AWD',
    batteryCapacity: 75.0,
    batteryType: 'NMC',
    rangeWLTP: 629,
    rangeNEDC: 0,
    rangeCLTC: 713,
    acChargePower: 11,
    dcChargePower: 250,
    voltageArchitecture: '400V',
    v2lSupport: false,
    v2lPower: 0
  },
  {
    brand: 'Tesla',
    model: 'Model 3',
    trim: 'Performance AWD',
    price: 2199000,
    image: '/images/tesla_model3.png',
    bodyType: 'Sedan',
    warrantyYears: 4,
    warrantyKm: 80000,
    length: 4720,
    width: 1850,
    height: 1441,
    wheelbase: 2875,
    cargoVolume: 594,
    frunkVolume: 88,
    horsepower: 510,
    torque: 741,
    acceleration0To100: 3.1,
    topSpeed: 262,
    driveType: 'AWD',
    batteryCapacity: 75.0,
    batteryType: 'NMC',
    rangeWLTP: 528,
    rangeNEDC: 0,
    rangeCLTC: 600,
    acChargePower: 11,
    dcChargePower: 250,
    voltageArchitecture: '400V',
    v2lSupport: false,
    v2lPower: 0
  },
  {
    brand: 'Tesla',
    model: 'Model Y',
    trim: 'Rear-Wheel Drive',
    price: 1499000,
    image: '/images/tesla_modely.png',
    bodyType: 'SUV',
    warrantyYears: 4,
    warrantyKm: 80000,
    length: 4751,
    width: 1921,
    height: 1624,
    wheelbase: 2890,
    cargoVolume: 854,
    frunkVolume: 117,
    horsepower: 299,
    torque: 420,
    acceleration0To100: 6.9,
    topSpeed: 217,
    driveType: 'RWD',
    batteryCapacity: 57.5,
    batteryType: 'LFP',
    rangeWLTP: 455,
    rangeNEDC: 0,
    rangeCLTC: 554,
    acChargePower: 11,
    dcChargePower: 170,
    voltageArchitecture: '400V',
    v2lSupport: false,
    v2lPower: 0
  },
  {
    brand: 'Tesla',
    model: 'Model Y',
    trim: 'Long Range AWD',
    price: 1749000,
    image: '/images/tesla_modely.png',
    bodyType: 'SUV',
    warrantyYears: 4,
    warrantyKm: 80000,
    length: 4751,
    width: 1921,
    height: 1624,
    wheelbase: 2890,
    cargoVolume: 854,
    frunkVolume: 117,
    horsepower: 514,
    torque: 493,
    acceleration0To100: 5.0,
    topSpeed: 217,
    driveType: 'AWD',
    batteryCapacity: 75.0,
    batteryType: 'NMC',
    rangeWLTP: 533,
    rangeNEDC: 0,
    rangeCLTC: 688,
    acChargePower: 11,
    dcChargePower: 250,
    voltageArchitecture: '400V',
    v2lSupport: false,
    v2lPower: 0
  },
  {
    brand: 'Tesla',
    model: 'Model Y',
    trim: 'Performance AWD',
    price: 2299000,
    image: '/images/tesla_modely.png',
    bodyType: 'SUV',
    warrantyYears: 4,
    warrantyKm: 80000,
    length: 4751,
    width: 1921,
    height: 1624,
    wheelbase: 2890,
    cargoVolume: 854,
    frunkVolume: 117,
    horsepower: 534,
    torque: 660,
    acceleration0To100: 3.7,
    topSpeed: 250,
    driveType: 'AWD',
    batteryCapacity: 75.0,
    batteryType: 'NMC',
    rangeWLTP: 514,
    rangeNEDC: 0,
    rangeCLTC: 615,
    acChargePower: 11,
    dcChargePower: 250,
    voltageArchitecture: '400V',
    v2lSupport: false,
    v2lPower: 0
  },

  // --- Deepal ---
  {
    brand: 'Deepal',
    model: 'S07',
    trim: 'L',
    price: 1399000,
    image: '/images/deepal_s07.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4750,
    width: 1930,
    height: 1625,
    wheelbase: 2900,
    cargoVolume: 435,
    frunkVolume: 125,
    horsepower: 258,
    torque: 320,
    acceleration0To100: 7.9,
    topSpeed: 180,
    driveType: 'RWD',
    batteryCapacity: 66.8,
    batteryType: 'NMC',
    rangeWLTP: 0,
    rangeNEDC: 485,
    rangeCLTC: 520,
    acChargePower: 7,
    dcChargePower: 87,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'Deepal',
    model: 'S07',
    trim: 'Standard',
    price: 1199000,
    image: '/images/deepal_s07.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4750,
    width: 1930,
    height: 1625,
    wheelbase: 2900,
    cargoVolume: 435,
    frunkVolume: 125,
    horsepower: 258,
    torque: 320,
    acceleration0To100: 8.2,
    topSpeed: 180,
    driveType: 'RWD',
    batteryCapacity: 56.1,
    batteryType: 'LFP',
    rangeWLTP: 0,
    rangeNEDC: 400,
    rangeCLTC: 410,
    acChargePower: 7,
    dcChargePower: 70,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'Deepal',
    model: 'L07',
    trim: 'S',
    price: 1329000,
    image: '/images/deepal_l07.png',
    bodyType: 'Sedan',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4820,
    width: 1890,
    height: 1480,
    wheelbase: 2900,
    cargoVolume: 435,
    frunkVolume: 70,
    horsepower: 258,
    torque: 320,
    acceleration0To100: 6.9,
    topSpeed: 180,
    driveType: 'RWD',
    batteryCapacity: 66.8,
    batteryType: 'NMC',
    rangeWLTP: 0,
    rangeNEDC: 540,
    rangeCLTC: 540,
    acChargePower: 7,
    dcChargePower: 87,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'Deepal',
    model: 'L07',
    trim: 'L (Extended)',
    price: 1429000,
    image: '/images/deepal_l07.png',
    bodyType: 'Sedan',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4820,
    width: 1890,
    height: 1480,
    wheelbase: 2900,
    cargoVolume: 435,
    frunkVolume: 70,
    horsepower: 218,
    torque: 320,
    acceleration0To100: 7.5,
    topSpeed: 180,
    driveType: 'RWD',
    batteryCapacity: 79.9,
    batteryType: 'NMC',
    rangeWLTP: 0,
    rangeNEDC: 640,
    rangeCLTC: 660,
    acChargePower: 7,
    dcChargePower: 87,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'Deepal',
    model: 'S05',
    trim: 'RWD Premium',
    price: 899000,
    image: '/images/deepal_s05.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4620,
    width: 1900,
    height: 1600,
    wheelbase: 2880,
    cargoVolume: 410,
    frunkVolume: 0,
    horsepower: 238,
    torque: 320,
    acceleration0To100: 7.3,
    topSpeed: 180,
    driveType: 'RWD',
    batteryCapacity: 56.1,
    batteryType: 'LFP',
    rangeWLTP: 0,
    rangeNEDC: 0,
    rangeCLTC: 510,
    acChargePower: 7,
    dcChargePower: 70,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'Deepal',
    model: 'S05',
    trim: 'RWD Lite',
    price: 799000,
    image: '/images/deepal_s05.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4620,
    width: 1900,
    height: 1600,
    wheelbase: 2880,
    cargoVolume: 410,
    frunkVolume: 0,
    horsepower: 238,
    torque: 320,
    acceleration0To100: 7.6,
    topSpeed: 180,
    driveType: 'RWD',
    batteryCapacity: 48.0,
    batteryType: 'LFP',
    rangeWLTP: 0,
    rangeNEDC: 0,
    rangeCLTC: 400,
    acChargePower: 7,
    dcChargePower: 60,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },

  // --- GAC ---
  {
    brand: 'GAC',
    model: 'Aion Y Plus',
    trim: '490 Premium',
    price: 859900,
    image: '/images/gac_aion_y_plus.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4535,
    width: 1870,
    height: 1650,
    wheelbase: 2750,
    cargoVolume: 405,
    frunkVolume: 0,
    horsepower: 204,
    torque: 225,
    acceleration0To100: 8.5,
    topSpeed: 150,
    driveType: 'FWD',
    batteryCapacity: 63.2,
    batteryType: 'LFP',
    rangeWLTP: 0,
    rangeNEDC: 490,
    rangeCLTC: 510,
    acChargePower: 7,
    dcChargePower: 80,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'GAC',
    model: 'Aion Y Plus',
    trim: '410 Elite',
    price: 699900,
    image: '/images/gac_aion_y_plus.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4535,
    width: 1870,
    height: 1650,
    wheelbase: 2750,
    cargoVolume: 405,
    frunkVolume: 0,
    horsepower: 136,
    torque: 176,
    acceleration0To100: 9.6,
    topSpeed: 150,
    driveType: 'FWD',
    batteryCapacity: 50.6,
    batteryType: 'LFP',
    rangeWLTP: 0,
    rangeNEDC: 410,
    rangeCLTC: 430,
    acChargePower: 7,
    dcChargePower: 60,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 2.2
  },
  {
    brand: 'GAC',
    model: 'Aion Y Plus',
    trim: '510 Ultra',
    price: 959900,
    image: '/images/gac_aion_y_plus.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 160000,
    length: 4535,
    width: 1870,
    height: 1650,
    wheelbase: 2750,
    cargoVolume: 405,
    frunkVolume: 0,
    horsepower: 204,
    torque: 225,
    acceleration0To100: 8.3,
    topSpeed: 150,
    driveType: 'FWD',
    batteryCapacity: 69.9,
    batteryType: 'LFP',
    rangeWLTP: 0,
    rangeNEDC: 510,
    rangeCLTC: 540,
    acChargePower: 7,
    dcChargePower: 80,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },

  // --- MG ---
  {
    brand: 'MG',
    model: 'MG 4',
    trim: 'Standard Range D',
    price: 709900,
    image: '/images/mg4_electric.png',
    bodyType: 'Hatchback',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4287,
    width: 1836,
    height: 1516,
    wheelbase: 2705,
    cargoVolume: 363,
    frunkVolume: 0,
    horsepower: 170,
    torque: 250,
    acceleration0To100: 7.5,
    topSpeed: 160,
    driveType: 'RWD',
    batteryCapacity: 51.0,
    batteryType: 'LFP',
    rangeWLTP: 350,
    rangeNEDC: 425,
    rangeCLTC: 450,
    acChargePower: 6.6,
    dcChargePower: 88,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 2.2
  },
  {
    brand: 'MG',
    model: 'MG 4',
    trim: 'Long Range V',
    price: 889900,
    image: '/images/mg4_electric.png',
    bodyType: 'Hatchback',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4287,
    width: 1836,
    height: 1516,
    wheelbase: 2705,
    cargoVolume: 363,
    frunkVolume: 0,
    horsepower: 245,
    torque: 350,
    acceleration0To100: 6.5,
    topSpeed: 180,
    driveType: 'RWD',
    batteryCapacity: 64.0,
    batteryType: 'NMC',
    rangeWLTP: 435,
    rangeNEDC: 540,
    rangeCLTC: 550,
    acChargePower: 11,
    dcChargePower: 140,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 2.2
  },
  {
    brand: 'MG',
    model: 'MG 4',
    trim: 'XPOWER AWD',
    price: 1119900,
    image: '/images/mg_4_xpower.png',
    bodyType: 'Hatchback',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4287,
    width: 1836,
    height: 1516,
    wheelbase: 2705,
    cargoVolume: 363,
    frunkVolume: 0,
    horsepower: 435,
    torque: 600,
    acceleration0To100: 3.8,
    topSpeed: 200,
    driveType: 'AWD',
    batteryCapacity: 64.0,
    batteryType: 'NMC',
    rangeWLTP: 385,
    rangeNEDC: 480,
    rangeCLTC: 0,
    acChargePower: 11,
    dcChargePower: 140,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 2.2
  },
  {
    brand: 'MG',
    model: 'S5',
    trim: 'Standard RWD',
    price: 859000,
    image: '/images/mg_s5.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4476,
    width: 1849,
    height: 1621,
    wheelbase: 2730,
    cargoVolume: 380,
    frunkVolume: 0,
    horsepower: 170,
    torque: 250,
    acceleration0To100: 8.6,
    topSpeed: 170,
    driveType: 'RWD',
    batteryCapacity: 49.1,
    batteryType: 'LFP',
    rangeWLTP: 0,
    rangeNEDC: 0,
    rangeCLTC: 425,
    acChargePower: 6.6,
    dcChargePower: 80,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 2.2
  },
  {
    brand: 'MG',
    model: 'S5',
    trim: 'Plus RWD',
    price: 929000,
    image: '/images/mg_s5.png',
    bodyType: 'SUV',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4476,
    width: 1849,
    height: 1621,
    wheelbase: 2730,
    cargoVolume: 380,
    frunkVolume: 0,
    horsepower: 170,
    torque: 250,
    acceleration0To100: 8.4,
    topSpeed: 170,
    driveType: 'RWD',
    batteryCapacity: 62.2,
    batteryType: 'LFP',
    rangeWLTP: 0,
    rangeNEDC: 0,
    rangeCLTC: 515,
    acChargePower: 6.6,
    dcChargePower: 85,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 2.2
  },
  {
    brand: 'MG',
    model: 'Cyberster',
    trim: 'RWD Single Motor',
    price: 2199000,
    image: '/images/mg_cyberster.png',
    bodyType: 'Others',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4535,
    width: 1913,
    height: 1329,
    wheelbase: 2690,
    cargoVolume: 249,
    frunkVolume: 0,
    horsepower: 340,
    torque: 475,
    acceleration0To100: 5.2,
    topSpeed: 195,
    driveType: 'RWD',
    batteryCapacity: 77.0,
    batteryType: 'NMC',
    rangeWLTP: 501,
    rangeNEDC: 0,
    rangeCLTC: 580,
    acChargePower: 11,
    dcChargePower: 140,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'MG',
    model: 'Cyberster',
    trim: 'AWD Dual Motor',
    price: 2499000,
    image: '/images/mg_cyberster.png',
    bodyType: 'Others',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4535,
    width: 1913,
    height: 1329,
    wheelbase: 2690,
    cargoVolume: 249,
    frunkVolume: 0,
    horsepower: 544,
    torque: 725,
    acceleration0To100: 3.2,
    topSpeed: 200,
    driveType: 'AWD',
    batteryCapacity: 77.0,
    batteryType: 'NMC',
    rangeWLTP: 443,
    rangeNEDC: 0,
    rangeCLTC: 503,
    acChargePower: 11,
    dcChargePower: 140,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },

  // --- GWM ---
  {
    brand: 'GWM',
    model: 'ORA Good Cat',
    trim: 'Pro',
    price: 799000,
    image: '/images/gwm_goodcat.png',
    bodyType: 'Hatchback',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4235,
    width: 1825,
    height: 1596,
    wheelbase: 2650,
    cargoVolume: 228,
    frunkVolume: 0,
    horsepower: 143,
    torque: 210,
    acceleration0To100: 8.9,
    topSpeed: 150,
    driveType: 'FWD',
    batteryCapacity: 48.6,
    batteryType: 'LFP',
    rangeWLTP: 310,
    rangeNEDC: 400,
    rangeCLTC: 0,
    acChargePower: 6.6,
    dcChargePower: 60,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'GWM',
    model: 'ORA Good Cat',
    trim: 'Ultra',
    price: 899000,
    image: '/images/gwm_goodcat.png',
    bodyType: 'Hatchback',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4235,
    width: 1825,
    height: 1596,
    wheelbase: 2650,
    cargoVolume: 228,
    frunkVolume: 0,
    horsepower: 143,
    torque: 210,
    acceleration0To100: 8.9,
    topSpeed: 150,
    driveType: 'FWD',
    batteryCapacity: 57.7,
    batteryType: 'LFP',
    rangeWLTP: 370,
    rangeNEDC: 500,
    rangeCLTC: 0,
    acChargePower: 6.6,
    dcChargePower: 60,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'GWM',
    model: 'ORA Good Cat',
    trim: 'GT',
    price: 1099000,
    image: '/images/gwm_goodcat.png',
    bodyType: 'Hatchback',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4254,
    width: 1848,
    height: 1596,
    wheelbase: 2650,
    cargoVolume: 228,
    frunkVolume: 0,
    horsepower: 171,
    torque: 250,
    acceleration0To100: 8.2,
    topSpeed: 160,
    driveType: 'FWD',
    batteryCapacity: 57.7,
    batteryType: 'LFP',
    rangeWLTP: 350,
    rangeNEDC: 460,
    rangeCLTC: 0,
    acChargePower: 6.6,
    dcChargePower: 60,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'GWM',
    model: 'ORA 07',
    trim: 'Long Range',
    price: 1299000,
    image: '/images/gwm_ora07.png',
    bodyType: 'Sedan',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4871,
    width: 1862,
    height: 1500,
    wheelbase: 2870,
    cargoVolume: 376,
    frunkVolume: 0,
    horsepower: 204,
    torque: 340,
    acceleration0To100: 7.9,
    topSpeed: 170,
    driveType: 'FWD',
    batteryCapacity: 83.5,
    batteryType: 'LFP',
    rangeWLTP: 550,
    rangeNEDC: 640,
    rangeCLTC: 650,
    acChargePower: 11,
    dcChargePower: 88,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'GWM',
    model: 'ORA 07',
    trim: 'Performance AWD',
    price: 1499000,
    image: '/images/gwm_ora07.png',
    bodyType: 'Sedan',
    warrantyYears: 8,
    warrantyKm: 180000,
    length: 4871,
    width: 1862,
    height: 1500,
    wheelbase: 2870,
    cargoVolume: 376,
    frunkVolume: 0,
    horsepower: 408,
    torque: 680,
    acceleration0To100: 4.3,
    topSpeed: 180,
    driveType: 'AWD',
    batteryCapacity: 83.5,
    batteryType: 'NMC',
    rangeWLTP: 483,
    rangeNEDC: 550,
    rangeCLTC: 600,
    acChargePower: 11,
    dcChargePower: 88,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },

  // --- Zeekr ---
  {
    brand: 'Zeekr',
    model: 'Zeekr X',
    trim: 'Standard RWD',
    price: 1199000,
    image: '/images/zeekr_x.png',
    bodyType: 'SUV',
    warrantyYears: 5,
    warrantyKm: 150000,
    length: 4432,
    width: 1836,
    height: 1566,
    wheelbase: 2750,
    cargoVolume: 362,
    frunkVolume: 0,
    horsepower: 272,
    torque: 343,
    acceleration0To100: 5.6,
    topSpeed: 180,
    driveType: 'RWD',
    batteryCapacity: 66,
    batteryType: 'LFP',
    rangeWLTP: 440,
    rangeNEDC: 0,
    rangeCLTC: 0,
    acChargePower: 22,
    dcChargePower: 150,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'Zeekr',
    model: 'Zeekr X',
    trim: 'Flagship AWD',
    price: 1349000,
    image: '/images/zeekr_x.png',
    bodyType: 'SUV',
    warrantyYears: 5,
    warrantyKm: 150000,
    length: 4432,
    width: 1836,
    height: 1566,
    wheelbase: 2750,
    cargoVolume: 362,
    frunkVolume: 0,
    horsepower: 428,
    torque: 543,
    acceleration0To100: 3.8,
    topSpeed: 180,
    driveType: 'AWD',
    batteryCapacity: 66,
    batteryType: 'LFP',
    rangeWLTP: 420,
    rangeNEDC: 0,
    rangeCLTC: 0,
    acChargePower: 22,
    dcChargePower: 150,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'Zeekr',
    model: 'Zeekr 009',
    trim: 'Single Motor RWD',
    price: 3099000,
    image: '/images/zeekr_009.png',
    bodyType: 'MPV',
    warrantyYears: 5,
    warrantyKm: 150000,
    length: 5209,
    width: 2024,
    height: 1848,
    wheelbase: 3205,
    cargoVolume: 590,
    frunkVolume: 0,
    horsepower: 422,
    torque: 520,
    acceleration0To100: 6.9,
    topSpeed: 200,
    driveType: 'RWD',
    batteryCapacity: 108,
    batteryType: 'NMC',
    rangeWLTP: 686,
    rangeNEDC: 0,
    rangeCLTC: 0,
    acChargePower: 11,
    dcChargePower: 205,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'Zeekr',
    model: 'Zeekr 009',
    trim: 'Dual Motor AWD',
    price: 3299000,
    image: '/images/zeekr_009.png',
    bodyType: 'MPV',
    warrantyYears: 5,
    warrantyKm: 150000,
    length: 5209,
    width: 2024,
    height: 1848,
    wheelbase: 3205,
    cargoVolume: 590,
    frunkVolume: 0,
    horsepower: 789,
    torque: 810,
    acceleration0To100: 4.5,
    topSpeed: 230,
    driveType: 'AWD',
    batteryCapacity: 108,
    batteryType: 'NMC',
    rangeWLTP: 582,
    rangeNEDC: 0,
    rangeCLTC: 0,
    acChargePower: 11,
    dcChargePower: 205,
    voltageArchitecture: '400V',
    v2lSupport: true,
    v2lPower: 3.3
  },

  // --- XPeng ---
  {
    brand: 'XPeng',
    model: 'XPeng G6',
    trim: 'Standard Range RWD',
    price: 1439000,
    image: '/images/xpeng_g6.png',
    bodyType: 'SUV',
    warrantyYears: 5,
    warrantyKm: 120000,
    length: 4753,
    width: 1920,
    height: 1650,
    wheelbase: 2890,
    cargoVolume: 571,
    frunkVolume: 0,
    horsepower: 258,
    torque: 440,
    acceleration0To100: 6.6,
    topSpeed: 200,
    driveType: 'RWD',
    batteryCapacity: 66,
    batteryType: 'LFP',
    rangeWLTP: 435,
    rangeNEDC: 0,
    rangeCLTC: 0,
    acChargePower: 11,
    dcChargePower: 215,
    voltageArchitecture: '800V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'XPeng',
    model: 'XPeng G6',
    trim: 'Long Range RWD',
    price: 1599000,
    image: '/images/xpeng_g6.png',
    bodyType: 'SUV',
    warrantyYears: 5,
    warrantyKm: 120000,
    length: 4753,
    width: 1920,
    height: 1650,
    wheelbase: 2890,
    cargoVolume: 571,
    frunkVolume: 0,
    horsepower: 285,
    torque: 440,
    acceleration0To100: 5.9,
    topSpeed: 200,
    driveType: 'RWD',
    batteryCapacity: 87.5,
    batteryType: 'NMC',
    rangeWLTP: 570,
    rangeNEDC: 0,
    rangeCLTC: 0,
    acChargePower: 11,
    dcChargePower: 280,
    voltageArchitecture: '800V',
    v2lSupport: true,
    v2lPower: 3.3
  },
  {
    brand: 'XPeng',
    model: 'XPeng G6',
    trim: 'Ultra Performance AWD',
    price: 1799000,
    image: '/images/xpeng_g6.png',
    bodyType: 'SUV',
    warrantyYears: 5,
    warrantyKm: 120000,
    length: 4753,
    width: 1920,
    height: 1650,
    wheelbase: 2890,
    cargoVolume: 571,
    frunkVolume: 0,
    horsepower: 487,
    torque: 660,
    acceleration0To100: 3.9,
    topSpeed: 200,
    driveType: 'AWD',
    batteryCapacity: 87.5,
    batteryType: 'NMC',
    rangeWLTP: 520,
    rangeNEDC: 0,
    rangeCLTC: 0,
    acChargePower: 11,
    dcChargePower: 280,
    voltageArchitecture: '800V',
    v2lSupport: true,
    v2lPower: 3.3
  }
];

export async function POST(request: Request) {
  try {
    const { passcode } = await request.json();
    const adminPasscode = process.env.ADMIN_PASSCODE || 'admin1234';

    if (passcode !== adminPasscode) {
      return NextResponse.json({ error: 'Unauthorized: Invalid passcode' }, { status: 401 });
    }

    await dbConnect();

    // Clear old data
    await EV.deleteMany({});
    await Review.deleteMany({});

    // Seed cars
    const createdCars = await EV.insertMany(initialCars);

    // Seed some reviews
    const seedReviews = [
      {
        evId: createdCars[0]._id, // BYD Atto 3 Extended
        userName: 'สมชาย ขับดี',
        rating: 5,
        ratingBattery: 5,
        ratingPerformance: 4,
        ratingComfort: 5,
        pros: 'ช่วงล่างนุ่มนวล ห้องโดยสารกว้างขวาง ดีไซน์ล้ำสมัย',
        cons: 'ระบบควบคุมแอร์ต้องปรับในจอสัมผัส ยุ่งยากเวลาขับรถ',
        comment: 'ใช้งานมา 6 เดือนแล้วครับ ประทับใจมาก ชาร์จไฟบ้าน Off-peak ประหยัดค่าเดินทางไปเยอะมาก แบตเตอรี่ LFP ถือว่าอึดและเสถียรดี',
        approved: true
      },
      {
        evId: createdCars[0]._id, // BYD Atto 3 Extended
        userName: 'วิภาวี สวยเก๋',
        rating: 4,
        ratingBattery: 4,
        ratingPerformance: 4,
        ratingComfort: 4,
        pros: 'อัตราเร่งดี แซงมั่นใจ หน้าจอหมุนได้สะดวกมากเวลาใช้แผนที่',
        cons: 'วัสดุห้องโดยสารบางจุดเป็นเบาะหนังสีสว่างเปื้อนง่าย',
        comment: 'โดยรวมประทับใจค่ะ มีระบบความปลอดภัยและระบบเตือนจังหวะต่างๆ ครบถ้วน ถือว่าคุ้มราคากับเงินที่จ่ายไปมาก',
        approved: true
      },
      {
        evId: createdCars[4]._id, // Tesla Model 3 RWD
        userName: 'อัครเดช ซิ่งไฟฟ้า',
        rating: 5,
        ratingBattery: 5,
        ratingPerformance: 5,
        ratingComfort: 3,
        pros: 'ระบบ Autopilot เทพมาก อัตราเร่ง 0-100 สะใจ รถเกาะถนนหนึบสุดๆ เครือข่าย Supercharger ชาร์จเร็วทันใจ',
        cons: 'ช่วงล่างค่อนข้างแข็งกระด้าง ไม่มีเบาะเป่าลมในรุ่นเก่า และไม่มีจอหลังพวงมาลัย',
        comment: 'สุดยอดรถซิ่งไฟฟ้าครับ ฟังก์ชันอัปเดตผ่าน OTA ตลอดเวลา รู้สึกเหมือนได้รถใหม่เรื่อยๆ การจัดการพลังงานดีเยี่ยม วิ่งทางไกลสบายใจสุดๆ',
        approved: true
      },
      {
        evId: createdCars[19]._id, // GAC Aion Y Plus 490 Premium (it shifted index)
        userName: 'สมหญิง รักครอบครัว',
        rating: 4,
        ratingBattery: 4,
        ratingPerformance: 3,
        ratingComfort: 5,
        pros: 'เบาะหลังพับแล้วกว้างเหมือนเตียงนอน ห้องโดยสารใหญ่มาก เหมาะกับครอบครัวที่มีเด็กและผู้สูงอายุ',
        cons: 'ความเร็วสูงสุดค่อนข้างต่ำ และดีไซน์ภายนอกดูอวบๆ ไปนิดนึง',
        comment: 'เหมาะเป็นรถครอบครัวนั่งสบายๆ เน้นพื้นที่กว้างขวาง อัตราเร่งไม่ได้จัดจ้านแต่ก็ใช้งานทั่วไปในเมืองหรือเที่ยวต่างจังหวัดสบายๆ ค่ะ',
        approved: true
      }
    ];

    await Review.insertMany(seedReviews);

    return NextResponse.json({
      success: true,
      message: 'Database seeded successfully with initial cars and reviews!',
      carsCount: createdCars.length,
      reviewsCount: seedReviews.length
    });

  } catch (error: any) {
    return NextResponse.json({ error: error.message || 'Internal Server Error' }, { status: 500 });
  }
}
